using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MaSch.Generators.Common
{
    public class SourceBuilder
    {
        private const int IdentCharCount = 4;

        private StringBuilder _builder;
        private int _currentIndent = 0;

        public SourceBuilder()
        {
            _builder = new StringBuilder(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

");
        }

        public IDisposable AddRegion(string regionName)
        {
            AppendLine($"#region {regionName}");
            return new CodeBlock(this, "#endregion", false);
        }
        public IDisposable AddBlock(string blockLine)
        {
            AppendLine(blockLine);
            return AddBlock();
        }
        public IDisposable AddBlock()
        {
            AppendLine("{");
            _currentIndent++;
            return new CodeBlock(this, "}", true);
        }

        public SourceBuilder AppendLine() => Append(Environment.NewLine);
        public SourceBuilder AppendLine(string value) => Append(value + Environment.NewLine);
        public SourceBuilder Append(string value)
        {
            var indent = new string(' ', _currentIndent * IdentCharCount);
            var lines = value.Replace("\r", "").Split(new[] { '\n' }, StringSplitOptions.None);
            foreach (var line in lines.Take(lines.Length - 1))
            {
                if (string.IsNullOrWhiteSpace(line))
                    _builder.AppendLine();
                else
                    _builder.Append(indent).AppendLine(line);
            }
            if (lines.Length > 1 && !string.IsNullOrWhiteSpace(lines[^1]))
                _builder.Append(indent);
            _builder.Append(lines[^1]);
            return this;
        }

        public override string ToString() => _builder.ToString();

        private class CodeBlock : IDisposable
        {
            private readonly SourceBuilder _builder;
            private readonly string _endContent;
            private readonly bool _changeIndent;

            public CodeBlock(SourceBuilder builder, string endContent, bool changeIndent)
            {
                _builder = builder;
                _endContent = endContent;
                _changeIndent = changeIndent;
            }

            public void Dispose()
            {
                if (_changeIndent)
                    _builder._currentIndent--;
                _builder.AppendLine(_endContent);
            }
        }
    }
}
