using MaSch.Generators.Support;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Runtime.CompilerServices;
using System.Text;

namespace MaSch.Generators.Common;

internal readonly struct StaticSourceCreator
{
    private static readonly string Header = SourceBuilder.AutoGeneratedFileHeader;
    private static readonly Encoding Encoding = Encoding.UTF8;

    private readonly Action<string, SourceText> _addSourceFunc;

    public StaticSourceCreator(Action<string, SourceText> addSourceFunc)
    {
        _addSourceFunc = addSourceFunc;
    }

    public StaticSourceCreator AddSource(
        string source,
        [CallerArgumentExpression("source")] string name = "")
    {
        var sourceText = source.StartsWith("//") ? source : Header + source;
        _addSourceFunc($"{name.Substring(10)}.g.cs", SourceText.From(sourceText, Encoding));
        return this;
    }
}
