//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaSch.Generators.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaSch.Generators.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.CodeAnalysis;
        ///using Microsoft.CodeAnalysis.Text;
        ///using System;
        ///using System.Text.RegularExpressions;
        ///
        ///#nullable enable
        ///
        ///namespace MaSch.Generators.Support
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Provides extensions for context interfaces providing &quot;AddSource&quot; methods.
        ///    /// &lt;/summary&gt;
        ///    public static class AddSourceExtensions
        ///    {
        ///        private static readonly char[] HexChars = new char[] { &apos;0&apos;, &apos;1&apos;, &apos;2&apos;, &apos;3&apos;, &apos;4&apos;, &apos;5&apos;, &apos;6&apos;, &apos;7&apos;, &apos;8&apos;, &apos;9&apos;, &apos;a&apos;, &apos;b&apos;, &apos;c&apos;, &apos;d&apos;, &apos;e&apos;, &apos;f&apos; };
        ///        pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddSourceExtensions {
            get {
                return ResourceManager.GetString("AddSourceExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.CodeAnalysis.Text;
        ///using System;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///#nullable enable
        ///
        ///namespace MaSch.Generators.Support
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Represents a in-memory source file.
        ///    /// &lt;/summary&gt;
        ///    public class SourceBuilder
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// The file header that is added to all source files generated using the &lt;see cref=&quot;SourceBuilder&quot;/&gt;.
        ///        /// &lt;/summary&gt;
        ///        public static readonly string AutoGeneratedFileHeade [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceBuilder {
            get {
                return ResourceManager.GetString("SourceBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.CodeAnalysis;
        ///using Microsoft.CodeAnalysis.CSharp;
        ///using Microsoft.CodeAnalysis.CSharp.Syntax;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Xml;
        ///
        ///#nullable enable
        ///
        ///namespace MaSch.Generators.Support
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Provides extensions for types implementing the &lt;see cref=&quot;ISymbol&quot;/&gt; interface.
        ///    /// &lt;/summary&gt;
        ///    public static class SymbolExtensions
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Format that can be used to get the u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SymbolExtensions {
            get {
                return ResourceManager.GetString("SymbolExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.CodeAnalysis;
        ///using Microsoft.CodeAnalysis.CSharp.Syntax;
        ///
        ///#nullable enable
        ///
        ///namespace MaSch.Generators.Support
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Provides extensions for &lt;see cref=&quot;SyntaxNode&quot;/&gt; as derived types.
        ///    /// &lt;/summary&gt;
        ///    public static class SyntaxExtensions
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Tries to get an attribute with a specific type name from the syntax node.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;memberDeclarationSyntax&quot;&gt;The syntax node.&lt;/param&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyntaxExtensions {
            get {
                return ResourceManager.GetString("SyntaxExtensions", resourceCulture);
            }
        }
    }
}
