//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaSch.Generators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaSch.Generators.StaticFiles", typeof(StaticFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MaSch.Core
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Represents C# access modifiers.
        ///    /// &lt;/summary&gt;
        ///    internal enum AccessModifier
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// The &lt;c&gt;public&lt;/c&gt; access modifier.
        ///        /// &lt;/summary&gt;
        ///        Public,
        ///
        ///        /// &lt;summary&gt;
        ///        /// The &lt;c&gt;protected internal&lt;/c&gt; access modifier.
        ///        /// &lt;/summary&gt;
        ///        ProtectedInternal,
        ///
        ///        /// &lt;summary&gt;
        ///        /// The &lt;c&gt;internal&lt;/c&gt; access modifier.
        ///        /// &lt;/summary&gt;
        ///        Internal,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessModifier {
            get {
                return ResourceManager.GetString("AccessModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///
        ///namespace MaSch.Core
        ///{
        ///    /// &lt;summary&gt;
        ///    /// When applied to a property inside an interface with the &lt;see cref=&quot;global::MaSch.Core.ObservablePropertyDefinitionAttribute&quot;/&gt;, sets the access modifier of the generated property.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;global::System.Attribute&quot; /&gt;
        ///    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
        ///    internal class ObservablePropertyAccessModifierAttribute : gl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObservablePropertyAccessModifierAttribute {
            get {
                return ResourceManager.GetString("ObservablePropertyAccessModifierAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MaSch.Core
        ///{
        ///    /// &lt;summary&gt;
        ///    /// When applied to an interface, the class that implements it will be marked for the ObservableObjectGenerator from
        ///    /// MaSch.Generators to automatically generate the properties as observable properties.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;global::System.Attribute&quot; /&gt;
        ///    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
        ///    internal class ObservablePropertyDefinitionAttribute : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObservablePropertyDefinitionAttribute {
            get {
                return ResourceManager.GetString("ObservablePropertyDefinitionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///
        ///namespace MaSch.Core
        ///{
        ///    /// &lt;summary&gt;
        ///    /// When applied to a class, the WrapperGenerator generator from MaSch.Generators will create wrapper members for the given type.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;global::System.Attribute&quot; /&gt;
        ///    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        ///    internal class WrappingAttribute : global::System.Attribute
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Initializes a ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrappingAttribute {
            get {
                return ResourceManager.GetString("WrappingAttribute", resourceCulture);
            }
        }
    }
}
