namespace MaSch.CodeAnalysis.CSharp.SourceGeneration;

public readonly struct StaticSourceCreator
{
    private readonly Encoding _encoding;
    private readonly Action<string, SourceText> _addSourceFunc;

    public StaticSourceCreator(Action<string, SourceText> addSourceFunc, Encoding? encoding = null)
    {
        _encoding = encoding ?? Encoding.UTF8;
        _addSourceFunc = addSourceFunc;
    }

    public StaticSourceCreator AddSource(
        string source,
        [CallerArgumentExpression(nameof(source))] string name = "")
    {
        var sourceText = source.StartsWith("//") ? source : SourceBuilder.AutoGeneratedFileHeader + source;
        _addSourceFunc($"{RemovePrefixFromName(name)}.g.cs", SourceText.From(sourceText, _encoding));
        return this;
    }

    private static string RemovePrefixFromName(string name)
    {
        var index = name.IndexOf('.');
        return index >= 0 ? name.Substring(index + 1) : name;
    }
}
